version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - REDIS_URL=redis://redis:6379
      - REDIS_ENABLE=true
    ports:
      - '${PORT}:3000'

  redis:
    image: redis:7.2.3-alpine3.19
    restart: unless-stopped
    volumes:
      - cache:/data

  mongodb:
    image: mongo:6.0.12
    restart: unless-stopped
    volumes:
      - ./data/mongo:/data/db
    ports:
      - '${MONGODB_EXTERNAL_PORT}:27017'

volumes:
  cache:
    driver: local