version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
    ports:
      - '${PORT}:3000'

  mongodb:
    image: mongo:6.0.12
    restart: unless-stopped
    volumes:
      - ./data/mongo:/data/db
    ports:
      - '${MONGODB_EXTERNAL_PORT}:27017'